version: '3.8'

services:
  facial-detection:
    build: .
    container_name: facial_detection_system
    restart: unless-stopped
    
    # Environment variables
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - CAMERA_SOURCE=${CAMERA_SOURCE:-0}
    
    # Volume mounts for persistence
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./config/.env:/app/config/.env:ro
      - ./config/settings.yaml:/app/config/settings.yaml:ro
    
    # Device access for camera
    devices:
      - /dev/video0:/dev/video0
    
    # Network configuration
    network_mode: host
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Optional: Add a web interface service
  # web-interface:
  #   build: ./web
  #   container_name: facial_detection_web
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - facial-detection
  #   environment:
  #     - API_URL=http://facial-detection:8000
