# Facial Detection System Configuration
# Epic 1 - Story Point 3: Configuration file

# Camera Configuration
camera:
  source: 0  # 0 for default webcam, or IP camera URL
  frame_width: 640
  frame_height: 480
  frame_skip_rate: 2  # Process every nth frame for optimization

# Face Recognition Settings
face_recognition:
  threshold: 0.6  # Similarity threshold (0.0 to 1.0)
  model: "hog"  # Options: "hog", "cnn"
  num_jitters: 1  # Number of times to re-sample face for encoding
  tolerance: 0.6  # Face distance tolerance

# Face Detection Settings
face_detection:
  scale_factor: 1.1  # How much the image size is reduced at each scale
  min_neighbors: 5  # How many neighbors each candidate rectangle should retain
  min_size: [30, 30]  # Minimum possible face size

# Telegram Bot Configuration
telegram:
  bot_token: "8233449278:AAHBzhJODian99m6SlDsyHl6kIpTD-QmIwQ"  # Your Telegram Bot Token (set via environment variable)
  chat_id: "6730084353"    # Your Telegram Chat ID (set via environment variable)
  enable_alerts: true
  alert_cooldown: 30  # Seconds between alerts for same unknown person

# Logging Configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  log_file: "logs/facial_detection.log"
  max_log_size: "10MB"
  backup_count: 5
  console_output: true

# Performance Settings
performance:
  max_fps: 30
  detection_interval: 0.1  # Seconds between face detections
  save_intruder_images: true
  image_quality: 95  # JPEG quality for saved images

# Database Settings
database:
  authorized_faces_dir: "data/authorized_faces"
  captured_intruders_dir: "data/captured_intruders"
  encodings_file: "data/face_encodings.pkl"

# System Settings
system:
  window_name: "Facial Detection System"
  show_video_feed: true
  show_bounding_boxes: true
  show_names: true
